# Generated by Django 5.1.4 on 2024-12-10 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventualidad',
            fields=[
                ('ideventualidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_eventualidad', models.CharField(max_length=200)),
                ('fecha_eventualidad', models.DateField()),
                ('tipo_eventualidad', models.CharField(max_length=20)),
                ('costo_eventualidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('responsable', models.CharField(max_length=100)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('idpromocion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_promocion', models.CharField(max_length=100)),
                ('valor_referencial_promo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_promocion', models.CharField(max_length=100)),
                ('porcentaje_promocion', models.IntegerField()),
                ('fecha_vigencia', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('estado_promocion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeEvento',
            fields=[
                ('idtipo_de_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=50)),
                ('url_imagen', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idevento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('valor_referencial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_horas_permitidas', models.IntegerField()),
                ('valor_extra_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_de_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventos.tipodeevento')),
            ],
        ),
    ]
