# Generated by Django 5.1.4 on 2024-12-24 20:25

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodeevento',
            name='url_imagen',
        ),
        migrations.AddField(
            model_name='evento',
            name='titulo_evento',
            field=models.CharField(default='Sin título', max_length=50),
        ),
        migrations.AddField(
            model_name='eventualidad',
            name='eventualidad_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventualidad', to='eventos.evento'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='tipo_de_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocion', to='eventos.tipodeevento'),
        ),
        migrations.AddField(
            model_name='tipodeevento',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='numero_horas_permitidas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='valor_extra_hora',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='valor_referencial',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='eventualidad',
            name='costo_eventualidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='eventualidad',
            name='tipo_eventualidad',
            field=models.CharField(default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='estado_promocion',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('caducado', 'Caducado'), ('n/a', 'N/A')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='porcentaje_promocion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='valor_referencial_promo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
