# Generated by Django 5.1.4 on 2024-12-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('idalquiler', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_alquiler', models.DateField()),
                ('horainicio_planificada_reserva', models.TimeField()),
                ('horafin_planificada_reserva', models.TimeField()),
                ('horafin_real_reserva', models.TimeField(blank=True, null=True)),
                ('costo_alquiler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calificacion_negocio', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cantidad_anticipo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_alquiler', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AlquilerServicio',
            fields=[
                ('idalquiler_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calificacion_cliente', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoAlquiler',
            fields=[
                ('idfoto_alquiler', models.AutoField(primary_key=True, serialize=False)),
                ('url_foto', models.URLField(max_length=255)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
    ]
