# Generated by Django 5.1.4 on 2024-12-24 20:25

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotoalquiler',
            name='url_foto',
        ),
        migrations.AddField(
            model_name='fotoalquiler',
            name='alquiler',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='alquileres.alquiler'),
        ),
        migrations.AddField(
            model_name='fotoalquiler',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='calificacion_negocio',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='cantidad_anticipo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='costo_alquiler',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='estado_alquiler',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='alquilerservicio',
            name='calificacion_cliente',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='alquilerservicio',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='alquilerservicio',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='fotoalquiler',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fotoalquiler',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
