# Generated by Django 5.1.4 on 2024-12-26 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0003_remove_fotoalquiler_url_foto_fotoalquiler_alquiler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='costo_alquiler',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
