# Generated by Django 5.1.4 on 2024-12-10 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idservicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_servicio', models.CharField(max_length=150)),
                ('valor_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_servicio', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('descripcion_unidad', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_actualizacion_precio', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoServicio',
            fields=[
                ('idfoto_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.URLField(max_length=255)),
                ('descripcion_foto', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
        ),
    ]
