# Generated by Django 5.1.4 on 2024-12-24 20:25

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotoservicio',
            name='url_imagen',
        ),
        migrations.AddField(
            model_name='fotoservicio',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='Nombre_servicio',
            field=models.CharField(default='Sin título', max_length=50),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_emision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fotoservicio',
            name='descripcion_foto',
            field=models.TextField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='fotoservicio',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fotoservicio',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion_servicio',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion_unidad',
            field=models.TextField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado_servicio',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('cancelado', 'Cancelado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='valor_unidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
